### ISSUE TITLE
type="hidden" validation with message

### ISSUE THREAD

**Issue by andrew-za** [psalmody/validate-bootstrap.jquery#8]
Hi, thanks for great plugin.

Validation works on the hidden inputs, but I would also like to see the red validation error messages, like on normal inputs?

**Comment by psalmody** [comment]
Why would you validate hidden inputs the user can't see? Can you post an example of what you're trying to do (jsfiddle or codepen)?

**Comment by andrew-za** [comment]
I have some js rating stars that set their value to a hidden input...

**Comment by psalmody** [comment]
As-is the code validates [custom valid handlers](https://github.com/psalmody/validate-bootstrap.jquery#custom-valid-handler) before checking if the element is hidden or not. You could write a custom valid handler for your hidden input and it should check that for validity.

Otherwise, you could try creating your ratings stars as radio inputs and requiring them. See [this codepen](https://codepen.io/lsirivong/pen/ekBxI) for an example I found.

**Comment by psalmody** [comment]
BTW, thanks for your input. Let me know if I can help clarify anything in the docs or code to make this work better. I've been using it several projects and it seems to work pretty well.
