### ISSUE TITLE
scrollTo & pattern check

### ISSUE THREAD

**Issue by LeonardoG67** [psalmody/validate-bootstrap.jquery#9]
[validate-bootstrap.jquery.zip](https://github.com/psalmody/validate-bootstrap.jquery/files/4386834/validate-bootstrap.jquery.zip)

**Comment by psalmody** [comment]
I'm not sure what this refers to. Can you submit a pull request or an issue that cites what code you changed? Closing until then.

Full disclosure haven't made edits to this package in a long time especially since HTML form validation is much better now. Bootstrap 4 docs have a great and simple way of implementing form validation now: 
https://getbootstrap.com/docs/4.0/components/forms/#validation
